Repository android/sunflower, pull requests merged in 2018-12, with the labels that each got.

#261 Update version of Kotlin and Navigation
  build.gradle
Labels: updates

#274 Allow links in plant descriptions.
  app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantDetailBindingAdapters.kt
  app/src/main/res/layout/fragment_plant_detail.xml
Labels: enhancement

#281 Add padding to bottom of plant description for FAB
  app/src/main/res/layout/fragment_plant_detail.xml
  app/src/main/res/values/dimens.xml
Labels: bug

#279 Update plant descriptions
  ASSETS_LICENSE
  README.md
  app/src/main/assets/plants.json
Labels: enhancement

#282 Update WorkManager to 1.0.0-alpha13
  app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
  build.gradle
Labels: updates

#284 Minor README updates for ktlint
  README.md
Labels: updates

#292 Update WorkManager to 1.0.0-beta01
  build.gradle
Labels: updates
