Repository android/sunflower, pull requests merged in 2019-06, with the labels that each got.

#421 Removed Google+ community reference since Google+ is shutdown.
  README.md
Labels: cleanup

#407 Oberve LiveData with Extension function
  app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
  app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
  app/src/main/java/com/google/samples/apps/sunflower/PlantListFragment.kt
Labels: enhancement

#431 Update Material version to 1.1.0-alpha07
  build.gradle
Labels: updates

#432 Add button to navigate to Plant List
  app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
  app/src/main/res/layout/fragment_garden.xml
  app/src/main/res/navigation/nav_garden.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#434 Use ktx function for findNavController in GardenActivity
  app/src/main/java/com/google/samples/apps/sunflower/GardenActivity.kt
Labels: enhancement

#422 Use non-changing strings for plant IDs
  app/src/main/assets/plants.json
Labels: enhancement

#423 Add two more plants to the plant database
  app/src/main/assets/plants.json
Labels: enhancement

#437 Turning Plant List Grid into Material Themed Cards
  app/src/main/java/com/google/samples/apps/sunflower/views/CustomCardView.kt
  app/src/main/res/layout/fragment_plant_list.xml
  app/src/main/res/layout/list_item_plant.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#439 Add collapsing title to ViewPager
  app/src/main/java/com/google/samples/apps/sunflower/ViewPagerFragment.kt
  app/src/main/res/layout/fragment_garden.xml
  app/src/main/res/layout/fragment_view_pager.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#442 Add app bar to plant detail page
  app/src/main/res/layout/fragment_plant_detail.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#453 Moved Grid Width to Integer.xml file.
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/integers.xml
Labels: cleanup

#454 Changed shape of FAB Plus button on detail page.
  app/src/main/res/layout/fragment_plant_detail.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#455 Changed shape and color of add button
  app/src/main/res/layout/fragment_garden.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#451 [UPDATE] support -> 1.1.0-beta01
  build.gradle
Labels: updates

#459 Rename variables for Gradle dependencies
  app/build.gradle
  build.gradle
Labels: updates

#461 Update tests for the new UI interface
  app/src/androidTest/java/com/google/samples/apps/sunflower/GardenActivityTest.kt
  app/src/androidTest/java/com/google/samples/apps/sunflower/PlantDetailFragmentTest.kt
Labels: enhancement

#468 Add icons to the tab layout
  README.md
  app/src/main/java/com/google/samples/apps/sunflower/ViewPagerFragment.kt
  app/src/main/res/drawable/ic_my_garden_active.xml
  app/src/main/res/drawable/ic_my_garden_inactive.xml
  app/src/main/res/drawable/ic_plant_list_active.xml
  app/src/main/res/drawable/ic_plant_list_inactive.xml
  app/src/main/res/values/colors.xml
Labels: enhancement
