Repository android/sunflower, pull requests merged in 2019-03, with the labels that each got.

#352 [UPDATE] navigation lib 1.0.0-rc02
  build.gradle
Labels: updates

#355 Update WorkManager to 1.0.0 stable
  build.gradle
Labels: updates

#354 Added french locales
  app/src/main/res/values-fr/strings.xml
Labels: enhancement

#357 [UPDATE] Gradle 3.3.2
  build.gradle
Labels: updates

#358 Update Navigation to 2.0.0-rc02
  app/build.gradle
  build.gradle
Labels: updates

#359 Use navArgs() instead of fromBundle() to retrieve args
  app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
Labels: enhancement

#360 Update WorkManager to 2.0.0-rc01
  app/build.gradle
  build.gradle
Labels: updates

#364 [OPTIMIZE] Optimize if-demand for hasPlantings and submitList
  app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
Labels: cleanup

#363 [FIX] #362, connectedCheck (androidTest) broken
  app/src/androidTest/java/com/google/samples/apps/sunflower/PlantDetailFragmentTest.kt
Labels: bug

#356 Add basic support for RecyclerView-selection
  app/build.gradle
  app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
  app/src/main/java/com/google/samples/apps/sunflower/adapters/GardenPlantingAdapter.kt
  app/src/main/java/com/google/samples/apps/sunflower/viewmodels/GardenPlantingListViewModel.kt
  app/src/main/res/drawable/list_item_garden_planting_background.xml
  app/src/main/res/layout/list_item_garden_planting.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#372 Update Navigation to 2.0.0 stable
  build.gradle
Labels: updates

#371 Add ActionMode framework.
  app/src/main/java/com/google/samples/apps/sunflower/GardenFragment.kt
  app/src/main/res/menu/menu_garden_action_mode.xml
Labels: enhancement

#375 Speed up animations.
  app/src/main/res/values/anim.xml
Labels: enhancement

#377 Upgrade WorkManager to 2.0.0 stable
  build.gradle
Labels: updates
