Repository android/sunflower, pull requests merged in 2019-01, with the labels that each got.

#286 [OPTIMIZE] #269: Move Diff callbacks into other files
  app/src/main/java/com/google/samples/apps/sunflower/adapters/GardenPlantDiffCallback.kt
  app/src/main/java/com/google/samples/apps/sunflower/adapters/GardenPlantingAdapter.kt
  app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantAdapter.kt
  app/src/main/java/com/google/samples/apps/sunflower/adapters/PlantDiffCallback.kt
Labels: cleanup

#297 Update Navigation and Constraint Layout versions
  app/src/main/java/com/google/samples/apps/sunflower/PlantDetailFragment.kt
  build.gradle
Labels: updates

#303 Update Gradle version to 3.3.0 to reflect Android Studio 3.3 release
  README.md
  build.gradle
Labels: updates

#304 Omit .applicationContext in SeedDatabaseWorker
  app/src/main/java/com/google/samples/apps/sunflower/workers/SeedDatabaseWorker.kt
Labels: cleanup

#307 [UPDATE] WorkManager 1.0.0-beta02
  build.gradle
Labels: updates

#310 Minor formatting fix.
  app/src/main/java/com/google/samples/apps/sunflower/utilities/InjectorUtils.kt
Labels: cleanup

#315 Fix double toolbar issue in Plant Details page
  app/src/main/res/layout/fragment_plant_detail.xml
Labels: bug, enhancement
