Repository android/sunflower, pull requests merged in 2019-02, with the labels that each got.

#318 Upgrade Navigation and Work versions
  build.gradle
Labels: updates

#319 [UPDATE] Gradle 3.3.1
  build.gradle
Labels: updates

#321 [UPDATE] Kotlin 1.3.21
  build.gradle
Labels: updates

#323 [UPDATE] Coroutines 1.1.1
  build.gradle
Labels: updates

#333 Reduced duration time of fragment transitions
  app/src/main/res/values/anim.xml
Labels: enhancement

#328 [FEATURE] Japanese support for issue #322
  app/src/main/res/values-ja/strings.xml
Labels: enhancement

#334 [UPDATE] ktlint 0.30.0
  build.gradle
Labels: updates

#335 [UPDATE] nav-lib 1.0.0-beta02
  build.gradle
Labels: updates

#324 [UPDATE] Work-lib to 1.0.0-beta05
  build.gradle
Labels: updates

#338 Minor comment text update (Chinese -> Japanese)
  app/src/main/res/values-ja/strings.xml
Labels: cleanup

#339 [UPDATE] Work-lib 1.0.0-rc01
  build.gradle
Labels: updates

#337 [FEATURE] Support German (Germany)
  app/src/main/res/values-de/strings.xml
Labels: enhancement

#350 Removing Kotlin EAP Maven entries
  build.gradle
Labels: cleanup
